// <auto-generated />
using System;
using Bullgate.Access.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bullgate.Access.Migrations.Migrations
{
    [DbContext(typeof(AccessDbContext))]
    partial class AccessDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bullgate.Access.Domain.Administration.AdminOperation", b =>
                {
                    b.Property<string>("CallerId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("caller_id");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<DateTimeOffset>("CommittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("committed_at");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("operator_id");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("permission");

                    b.Property<Guid?>("RealmId")
                        .HasColumnType("uuid")
                        .HasColumnName("realm_id");

                    b.Property<byte[]>("RequestFingerprint")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("request_fingerprint");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("scope_id");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("session_id");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.HasKey("CallerId", "OperationId");

                    b.ToTable("admin_operations", null, t =>
                        {
                            t.HasCheckConstraint("ck_admin_operations_fingerprint", "octet_length(request_fingerprint) = 32");

                            t.HasCheckConstraint("ck_admin_operations_result", "jsonb_typeof(result_json) = 'object'");
                        });
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Flows.AccessFlow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AppEnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_environment_id");

                    b.Property<Guid>("ApplicationClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_client_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentRevision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("current_revision");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<Guid>("IntegrationClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_client_id");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("intent");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("integer")
                        .HasColumnName("protocol_version");

                    b.Property<Guid>("RealmId")
                        .HasColumnType("uuid")
                        .HasColumnName("realm_id");

                    b.Property<Guid?>("RegistrationContextId")
                        .HasColumnType("uuid")
                        .HasColumnName("registration_context_id");

                    b.Property<Guid>("SourceSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_access_flows");

                    b.HasIndex("ApplicationClientId")
                        .HasDatabaseName("ix_access_flows_application_client");

                    b.HasIndex("IntegrationClientId")
                        .HasDatabaseName("ix_access_flows_integration_client");

                    b.HasIndex("RegistrationContextId")
                        .HasDatabaseName("ix_access_flows_registration_context");

                    b.HasIndex("SourceSessionId")
                        .HasDatabaseName("ix_access_flows_source_session");

                    b.HasIndex("AppEnvironmentId", "Status")
                        .HasDatabaseName("ix_access_flows_environment_status");

                    b.HasIndex("IdentityId", "AppEnvironmentId")
                        .HasDatabaseName("ix_access_flows_identity_environment");

                    b.HasIndex("RealmId", "IdentityId")
                        .HasDatabaseName("ix_access_flows_realm_identity");

                    b.HasIndex("SourceSessionId", "Intent")
                        .IsUnique()
                        .HasDatabaseName("ux_access_flows_active_source_session_intent")
                        .HasFilter("status = 'Active'");

                    b.ToTable("access_flows", null, t =>
                        {
                            t.HasCheckConstraint("ck_access_flows_completion", "(status = 'Active' AND completed_at IS NULL) OR (status IN ('Completed', 'Expired', 'Cancelled') AND completed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_access_flows_current_revision", "current_revision > 0");

                            t.HasCheckConstraint("ck_access_flows_expiration", "expires_at > created_at");

                            t.HasCheckConstraint("ck_access_flows_intent", "intent IN ('ContinueRegistration', 'ManagePhone')");

                            t.HasCheckConstraint("ck_access_flows_intent_context", "(intent = 'ContinueRegistration' AND registration_context_id IS NOT NULL) OR (intent = 'ManagePhone' AND registration_context_id IS NULL)");

                            t.HasCheckConstraint("ck_access_flows_protocol_version", "protocol_version > 0");

                            t.HasCheckConstraint("ck_access_flows_status", "status IN ('Active', 'Completed', 'Expired', 'Cancelled')");

                            t.HasCheckConstraint("ck_access_flows_updated_at", "updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Flows.AccessFlowDataSubject", b =>
                {
                    b.Property<Guid>("FlowId")
                        .HasColumnType("uuid")
                        .HasColumnName("flow_id");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("RealmId")
                        .HasColumnType("uuid")
                        .HasColumnName("realm_id");

                    b.HasKey("FlowId", "IdentityId")
                        .HasName("pk_access_flow_data_subjects");

                    b.HasIndex("RealmId", "IdentityId", "FlowId")
                        .HasDatabaseName("ix_access_flow_data_subjects_realm_identity_flow");

                    b.ToTable("access_flow_data_subjects", (string)null);
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Flows.AccessFlowRequest", b =>
                {
                    b.Property<Guid>("IntegrationClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_client_id");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("uuid")
                        .HasColumnName("flow_id");

                    b.Property<Guid?>("IssuedSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_session_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<byte[]>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payload_hash");

                    b.Property<int?>("ResultRevision")
                        .HasColumnType("integer")
                        .HasColumnName("result_revision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.HasKey("IntegrationClientId", "RequestId")
                        .HasName("pk_access_flow_requests");

                    b.HasIndex("FlowId")
                        .IsUnique()
                        .HasDatabaseName("ux_access_flow_requests_pending_external_flow")
                        .HasFilter("status = 'PendingExternal'");

                    b.HasIndex("IssuedSessionId")
                        .HasDatabaseName("ix_access_flow_requests_issued_session");

                    b.HasIndex("FlowId", "ResultRevision")
                        .HasDatabaseName("ix_access_flow_requests_flow_revision");

                    b.ToTable("access_flow_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_access_flow_requests_completion", "(status = 'Committed' AND result_revision IS NOT NULL) OR (status IN ('PendingExternal', 'ExternalFailed') AND result_revision IS NULL AND issued_session_id IS NULL)");

                            t.HasCheckConstraint("ck_access_flow_requests_kind", "kind IN ('Start', 'Action')");

                            t.HasCheckConstraint("ck_access_flow_requests_payload_hash_length", "octet_length(payload_hash) = 32");

                            t.HasCheckConstraint("ck_access_flow_requests_result_revision", "result_revision IS NULL OR result_revision > 0");

                            t.HasCheckConstraint("ck_access_flow_requests_status", "status IN ('PendingExternal', 'Committed', 'ExternalFailed')");
                        });
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Flows.AccessFlowRevision", b =>
                {
                    b.Property<Guid>("FlowId")
                        .HasColumnType("uuid")
                        .HasColumnName("flow_id");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot");

                    b.HasKey("FlowId", "Revision")
                        .HasName("pk_access_flow_revisions");

                    b.ToTable("access_flow_revisions", null, t =>
                        {
                            t.HasCheckConstraint("ck_access_flow_revisions_revision", "revision > 0");
                        });
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Identities.Identity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Active")
                        .HasColumnName("lifecycle_state");

                    b.Property<Guid>("RealmId")
                        .HasColumnType("uuid")
                        .HasColumnName("realm_id");

                    b.HasKey("Id")
                        .HasName("pk_identities");

                    b.HasAlternateKey("RealmId", "Id")
                        .HasName("ak_identities_realm_id");

                    b.ToTable("identities", null, t =>
                        {
                            t.HasCheckConstraint("ck_identities_lifecycle", "lifecycle_state IN ('Active', 'Abandoned')");
                        });
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Identities.IdentityIdentifier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_value");

                    b.Property<Guid>("RealmId")
                        .HasColumnType("uuid")
                        .HasColumnName("realm_id");

                    b.Property<string>("Scheme")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("scheme");

                    b.Property<string>("VerificationMethod")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("verification_method");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id")
                        .HasName("pk_identity_identifiers");

                    b.HasIndex("RealmId", "IdentityId", "Scheme")
                        .IsUnique()
                        .HasDatabaseName("ux_identity_identifiers_realm_identity_scheme");

                    b.HasIndex("RealmId", "Scheme", "NormalizedValue")
                        .IsUnique()
                        .HasDatabaseName("ux_identity_identifiers_realm_scheme_value");

                    b.ToTable("identity_identifiers", null, t =>
                        {
                            t.HasCheckConstraint("ck_identity_identifiers_verification", "(verified_at IS NULL AND verification_method IS NULL) OR (verified_at IS NOT NULL AND verification_method IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Identities.IdentityProof", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccessFlowId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_flow_id");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uuid")
                        .HasColumnName("challenge_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<Guid?>("SubjectIdentifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_identifier_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_identity_proofs");

                    b.HasIndex("ChallengeId")
                        .IsUnique()
                        .HasDatabaseName("ux_identity_proofs_challenge");

                    b.HasIndex("IdentityId")
                        .HasDatabaseName("ix_identity_proofs_identity");

                    b.HasIndex("SubjectIdentifierId")
                        .HasDatabaseName("ix_identity_proofs_subject_identifier");

                    b.HasIndex("AccessFlowId", "Type")
                        .HasDatabaseName("ix_identity_proofs_flow_type");

                    b.ToTable("identity_proofs", (string)null);
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Identities.IdentitySession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AppEnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_environment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Product")
                        .HasColumnName("purpose");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_identity_sessions");

                    b.HasIndex("AppEnvironmentId")
                        .HasDatabaseName("ix_identity_sessions_environment");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_identity_sessions_token_hash");

                    b.HasIndex("IdentityId", "AppEnvironmentId")
                        .HasDatabaseName("ix_identity_sessions_identity_environment");

                    b.ToTable("identity_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_identity_sessions_expiration", "expires_at > created_at");

                            t.HasCheckConstraint("ck_identity_sessions_purpose", "purpose IN ('Product', 'Registration')");

                            t.HasCheckConstraint("ck_identity_sessions_revocation", "revoked_at IS NULL OR revoked_at >= created_at");

                            t.HasCheckConstraint("ck_identity_sessions_token_hash_length", "octet_length(token_hash) = 32");
                        });
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Identities.PasswordCredential", b =>
                {
                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdentityId")
                        .HasName("pk_password_credentials");

                    b.ToTable("password_credentials", (string)null);
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Identities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AppEnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_environment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_tokens");

                    b.HasIndex("AppEnvironmentId")
                        .HasDatabaseName("ix_password_reset_tokens_environment");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_password_reset_tokens_token_hash");

                    b.HasIndex("IdentityId", "CreatedAt")
                        .HasDatabaseName("ix_password_reset_tokens_identity_created_at");

                    b.ToTable("password_reset_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_password_reset_tokens_expiration", "expires_at > created_at");

                            t.HasCheckConstraint("ck_password_reset_tokens_hash_length", "octet_length(token_hash) = 32");

                            t.HasCheckConstraint("ck_password_reset_tokens_used", "used_at IS NULL OR (used_at >= created_at AND used_at < expires_at)");
                        });
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Identities.PhonePasswordResetChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AppEnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_environment_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset?>("ProviderApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("provider_approved_at");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_reference");

                    b.Property<DateTimeOffset>("ResendAvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resend_available_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_phone_password_reset_challenges");

                    b.HasIndex("AppEnvironmentId", "Phone")
                        .HasDatabaseName("ix_phone_password_reset_challenges_environment_phone");

                    b.HasIndex("IdentityId", "AppEnvironmentId")
                        .IsUnique()
                        .HasDatabaseName("ux_phone_password_reset_challenges_open_identity_environment")
                        .HasFilter("status IN ('PendingDelivery', 'Active', 'Confirming')");

                    b.HasIndex("IdentityId", "CreatedAt")
                        .HasDatabaseName("ix_phone_password_reset_challenges_identity_created");

                    b.ToTable("phone_password_reset_challenges", null, t =>
                        {
                            t.HasCheckConstraint("ck_phone_password_reset_challenges_attempts", "attempts >= 0 AND attempts <= max_attempts AND max_attempts > 0");

                            t.HasCheckConstraint("ck_phone_password_reset_challenges_code_hash_length", "octet_length(code_hash) = 32");

                            t.HasCheckConstraint("ck_phone_password_reset_challenges_completed_approval", "status <> 'Completed' OR provider_approved_at IS NOT NULL");

                            t.HasCheckConstraint("ck_phone_password_reset_challenges_completion", "(status IN ('PendingDelivery', 'Active', 'Confirming') AND completed_at IS NULL) OR (status IN ('Completed', 'Superseded', 'Exhausted', 'DeliveryFailed') AND completed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_phone_password_reset_challenges_expiration", "expires_at > created_at AND resend_available_at >= created_at");

                            t.HasCheckConstraint("ck_phone_password_reset_challenges_provider_approval", "provider_approved_at IS NULL OR (provider_approved_at >= created_at AND (completed_at IS NULL OR provider_approved_at <= completed_at))");
                        });
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Identities.PhoneRegistrationConflict", b =>
                {
                    b.Property<Guid>("AccessFlowId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_flow_id");

                    b.Property<Guid>("ConflictingPhoneIdentifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("conflicting_phone_identifier_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EmailResolutionExhaustedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_resolution_exhausted_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("FailedEmailAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_email_attempts");

                    b.Property<Guid>("PreviousIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_identity_id");

                    b.HasKey("AccessFlowId")
                        .HasName("pk_phone_registration_conflicts");

                    b.HasIndex("ConflictingPhoneIdentifierId")
                        .HasDatabaseName("ix_phone_registration_conflicts_phone_identifier");

                    b.HasIndex("PreviousIdentityId")
                        .HasDatabaseName("ix_phone_registration_conflicts_previous_identity");

                    b.ToTable("phone_registration_conflicts", null, t =>
                        {
                            t.HasCheckConstraint("ck_phone_registration_conflicts_attempts", "failed_email_attempts >= 0");

                            t.HasCheckConstraint("ck_phone_registration_conflicts_email_exhaustion", "email_resolution_exhausted_at IS NULL OR (email_resolution_exhausted_at >= created_at AND email_resolution_exhausted_at < expires_at AND failed_email_attempts > 0)");

                            t.HasCheckConstraint("ck_phone_registration_conflicts_expiration", "expires_at > created_at");
                        });
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Identities.ProofAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uuid")
                        .HasColumnName("challenge_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("outcome");

                    b.HasKey("Id")
                        .HasName("pk_proof_attempts");

                    b.HasIndex("ChallengeId", "AttemptedAt")
                        .HasDatabaseName("ix_proof_attempts_challenge_attempted");

                    b.ToTable("proof_attempts", (string)null);
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Identities.ProofChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccessFlowId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_flow_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DestinationScheme")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("destination_scheme");

                    b.Property<string>("DestinationValue")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("destination_value");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_reference");

                    b.Property<DateTimeOffset>("ResendAvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resend_available_at");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_proof_challenges");

                    b.HasIndex("IdentityId", "Type", "CreatedAt")
                        .HasDatabaseName("ix_proof_challenges_identity_type_created");

                    b.HasIndex(new[] { "AccessFlowId", "Type" }, "IX_ProofChallenges_AccessFlowId_Type_Active")
                        .IsUnique()
                        .HasDatabaseName("ux_proof_challenges_active_flow_type")
                        .HasFilter("status = 'Active'");

                    b.HasIndex(new[] { "AccessFlowId", "Type" }, "IX_ProofChallenges_AccessFlowId_Type_Confirming")
                        .IsUnique()
                        .HasDatabaseName("ux_proof_challenges_confirming_flow_type")
                        .HasFilter("status = 'Confirming'");

                    b.HasIndex(new[] { "AccessFlowId", "Type" }, "IX_ProofChallenges_AccessFlowId_Type_PendingDelivery")
                        .IsUnique()
                        .HasDatabaseName("ux_proof_challenges_pending_delivery_flow_type")
                        .HasFilter("status = 'PendingDelivery'");

                    b.ToTable("proof_challenges", null, t =>
                        {
                            t.HasCheckConstraint("ck_proof_challenges_attempts", "attempts >= 0 AND attempts <= max_attempts AND max_attempts > 0");

                            t.HasCheckConstraint("ck_proof_challenges_completion", "(status IN ('PendingDelivery', 'Active', 'Confirming') AND completed_at IS NULL) OR (status IN ('DeliveryFailed', 'Verified', 'Superseded', 'Exhausted') AND completed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_proof_challenges_expiration", "expires_at > created_at AND resend_available_at >= created_at");

                            t.HasCheckConstraint("ck_proof_challenges_secret_hash_length", "octet_length(secret_hash) = 32");
                        });
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Identities.RegistrationContext", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AppEnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_environment_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<Guid>("RealmId")
                        .HasColumnType("uuid")
                        .HasColumnName("realm_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_registration_contexts");

                    b.HasIndex("AppEnvironmentId", "IdentityId")
                        .IsUnique()
                        .HasDatabaseName("ux_registration_contexts_environment_identity");

                    b.HasIndex("RealmId", "IdentityId")
                        .HasDatabaseName("ix_registration_contexts_realm_identity");

                    b.ToTable("registration_contexts", null, t =>
                        {
                            t.HasCheckConstraint("ck_registration_contexts_closure", "closed_at IS NULL OR closed_at >= created_at");

                            t.HasCheckConstraint("ck_registration_contexts_status", "(status = 'Open' AND closed_at IS NULL) OR (status IN ('Completed', 'Abandoned') AND closed_at IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Identities.SocialCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<Guid>("RealmId")
                        .HasColumnType("uuid")
                        .HasColumnName("realm_id");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_social_credentials");

                    b.HasIndex("RealmId", "IdentityId")
                        .HasDatabaseName("ix_social_credentials_realm_identity");

                    b.HasIndex("RealmId", "Provider", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ux_social_credentials_realm_provider_subject");

                    b.ToTable("social_credentials", (string)null);
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Topology.App", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_apps");

                    b.HasAlternateKey("WorkspaceId", "Id")
                        .HasName("ak_apps_workspace_id");

                    b.HasIndex("WorkspaceId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_apps_workspace_key");

                    b.ToTable("apps", (string)null);
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Topology.AppEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_id");

                    b.Property<bool>("AppleAuthenticatorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("apple_authenticator_enabled");

                    b.Property<byte[]>("ConfigurationCiphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("configuration_ciphertext");

                    b.Property<int>("ConfigurationFormatVersion")
                        .HasColumnType("integer")
                        .HasColumnName("configuration_format_version");

                    b.Property<byte[]>("ConfigurationNonce")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("configuration_nonce");

                    b.Property<byte[]>("ConfigurationTag")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("configuration_tag");

                    b.Property<DateTimeOffset>("ConfigurationUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("configuration_updated_at");

                    b.Property<string>("CpfCollectionPosition")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cpf_collection_position");

                    b.Property<bool>("CpfIdentifierEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("cpf_identifier_enabled");

                    b.Property<bool>("CpfIdentifierRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("cpf_identifier_required");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("EmailIdentifierEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("email_identifier_enabled");

                    b.Property<bool>("EmailIdentifierRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("email_identifier_required");

                    b.Property<bool>("EmailVerificationEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verification_enabled");

                    b.Property<string>("EmailVerificationProvider")
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("email_verification_provider");

                    b.Property<bool>("GoogleAuthenticatorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("google_authenticator_enabled");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<bool>("PasswordAuthenticatorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("password_authenticator_enabled");

                    b.Property<string>("PasswordRecoveryUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("password_recovery_url");

                    b.Property<bool>("PhoneIdentifierEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_identifier_enabled");

                    b.Property<bool>("PhoneIdentifierRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_identifier_required");

                    b.Property<bool>("PhoneVerificationEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_verification_enabled");

                    b.Property<string>("PhoneVerificationProvider")
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("phone_verification_provider");

                    b.Property<Guid>("RealmId")
                        .HasColumnType("uuid")
                        .HasColumnName("realm_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_app_environments");

                    b.HasIndex("AppId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_app_environments_app_key");

                    b.HasIndex("WorkspaceId", "AppId")
                        .HasDatabaseName("ix_app_environments_workspace_app");

                    b.HasIndex("WorkspaceId", "RealmId")
                        .HasDatabaseName("ix_app_environments_workspace_realm");

                    b.ToTable("app_environments", null, t =>
                        {
                            t.HasCheckConstraint("ck_app_environments_configuration_ciphertext_length", "octet_length(configuration_ciphertext) > 0");

                            t.HasCheckConstraint("ck_app_environments_configuration_format", "configuration_format_version = 2");

                            t.HasCheckConstraint("ck_app_environments_configuration_nonce_length", "octet_length(configuration_nonce) = 12");

                            t.HasCheckConstraint("ck_app_environments_configuration_tag_length", "octet_length(configuration_tag) = 16");

                            t.HasCheckConstraint("ck_app_environments_cpf_after_required_phone", "cpf_collection_position IS DISTINCT FROM 'AfterPhone' OR (phone_identifier_enabled AND phone_identifier_required)");
                        });
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Topology.ApplicationClient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AppEnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_environment_id");

                    b.Property<string>("ApplicationId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("application_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("platform");

                    b.Property<string>("SigningIdentity")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("signing_identity");

                    b.Property<string>("SmsRetrieverAppHash")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("sms_retriever_app_hash");

                    b.HasKey("Id")
                        .HasName("pk_application_clients");

                    b.HasIndex("AppEnvironmentId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_application_clients_environment_key");

                    b.HasIndex("AppEnvironmentId", "Platform", "ApplicationId", "SigningIdentity")
                        .IsUnique()
                        .HasDatabaseName("ux_application_clients_artifact_identity")
                        .HasFilter("application_id IS NOT NULL");

                    b.ToTable("application_clients", null, t =>
                        {
                            t.HasCheckConstraint("ck_application_clients_sms_retriever_app_hash_length", "sms_retriever_app_hash IS NULL OR char_length(sms_retriever_app_hash) = 11");

                            t.HasCheckConstraint("ck_application_clients_sms_retriever_app_hash_platform", "sms_retriever_app_hash IS NULL OR platform = 'Android'");
                        });
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Topology.IntegrationClient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AppEnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_environment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_integration_clients");

                    b.HasIndex("AppEnvironmentId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_integration_clients_environment_key");

                    b.ToTable("integration_clients", (string)null);
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Topology.IntegrationClientPermission", b =>
                {
                    b.Property<Guid>("IntegrationClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_client_id");

                    b.Property<string>("Value")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permission");

                    b.HasKey("IntegrationClientId", "Value")
                        .HasName("pk_integration_client_permissions");

                    b.ToTable("integration_client_permissions", (string)null);
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Topology.IntegrationClientSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("HashAlgorithm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("hash_algorithm");

                    b.Property<Guid>("IntegrationClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_client_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.HasKey("Id")
                        .HasName("pk_integration_client_secrets");

                    b.HasIndex("IntegrationClientId")
                        .HasDatabaseName("ix_integration_client_secrets_client");

                    b.ToTable("integration_client_secrets", null, t =>
                        {
                            t.HasCheckConstraint("ck_integration_client_secrets_expiration", "expires_at IS NULL OR expires_at > created_at");

                            t.HasCheckConstraint("ck_integration_client_secrets_revocation", "revoked_at IS NULL OR revoked_at >= created_at");

                            t.HasCheckConstraint("ck_integration_client_secrets_sha256_length", "hash_algorithm <> 'sha256-v1' OR octet_length(secret_hash) = 32");
                        });
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Topology.Realm", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_realms");

                    b.HasAlternateKey("WorkspaceId", "Id")
                        .HasName("ak_realms_workspace_id");

                    b.HasIndex("WorkspaceId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_realms_workspace_key");

                    b.ToTable("realms", (string)null);
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Topology.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ux_workspaces_key");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Flows.AccessFlow", b =>
                {
                    b.HasOne("Bullgate.Access.Domain.Topology.AppEnvironment", null)
                        .WithMany()
                        .HasForeignKey("AppEnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_access_flows_app_environments");

                    b.HasOne("Bullgate.Access.Domain.Topology.ApplicationClient", null)
                        .WithMany()
                        .HasForeignKey("ApplicationClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_access_flows_application_clients");

                    b.HasOne("Bullgate.Access.Domain.Topology.IntegrationClient", null)
                        .WithMany()
                        .HasForeignKey("IntegrationClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_access_flows_integration_clients");

                    b.HasOne("Bullgate.Access.Domain.Identities.RegistrationContext", null)
                        .WithMany()
                        .HasForeignKey("RegistrationContextId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_access_flows_registration_contexts");

                    b.HasOne("Bullgate.Access.Domain.Identities.IdentitySession", null)
                        .WithMany()
                        .HasForeignKey("SourceSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_access_flows_source_sessions");

                    b.HasOne("Bullgate.Access.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("RealmId", "IdentityId")
                        .HasPrincipalKey("RealmId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_access_flows_identities");
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Flows.AccessFlowDataSubject", b =>
                {
                    b.HasOne("Bullgate.Access.Domain.Flows.AccessFlow", null)
                        .WithMany()
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_flow_data_subjects_flows");

                    b.HasOne("Bullgate.Access.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("RealmId", "IdentityId")
                        .HasPrincipalKey("RealmId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_access_flow_data_subjects_identities");
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Flows.AccessFlowRequest", b =>
                {
                    b.HasOne("Bullgate.Access.Domain.Flows.AccessFlow", null)
                        .WithMany()
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_flow_requests_flows");

                    b.HasOne("Bullgate.Access.Domain.Topology.IntegrationClient", null)
                        .WithMany()
                        .HasForeignKey("IntegrationClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_access_flow_requests_integration_clients");

                    b.HasOne("Bullgate.Access.Domain.Identities.IdentitySession", null)
                        .WithMany()
                        .HasForeignKey("IssuedSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_access_flow_requests_issued_sessions");

                    b.HasOne("Bullgate.Access.Domain.Flows.AccessFlowRevision", null)
                        .WithMany()
                        .HasForeignKey("FlowId", "ResultRevision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_access_flow_requests_revisions");
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Flows.AccessFlowRevision", b =>
                {
                    b.HasOne("Bullgate.Access.Domain.Flows.AccessFlow", null)
                        .WithMany()
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_flow_revisions_flows");
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Identities.Identity", b =>
                {
                    b.HasOne("Bullgate.Access.Domain.Topology.Realm", null)
                        .WithMany()
                        .HasForeignKey("RealmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_identities_realms");
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Identities.IdentityIdentifier", b =>
                {
                    b.HasOne("Bullgate.Access.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("RealmId", "IdentityId")
                        .HasPrincipalKey("RealmId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_identity_identifiers_identities");
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Identities.IdentityProof", b =>
                {
                    b.HasOne("Bullgate.Access.Domain.Flows.AccessFlow", null)
                        .WithMany()
                        .HasForeignKey("AccessFlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_identity_proofs_access_flows");

                    b.HasOne("Bullgate.Access.Domain.Identities.ProofChallenge", null)
                        .WithMany()
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_identity_proofs_challenges");

                    b.HasOne("Bullgate.Access.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_identity_proofs_identities");

                    b.HasOne("Bullgate.Access.Domain.Identities.IdentityIdentifier", null)
                        .WithMany()
                        .HasForeignKey("SubjectIdentifierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_identity_proofs_subject_identifiers");
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Identities.IdentitySession", b =>
                {
                    b.HasOne("Bullgate.Access.Domain.Topology.AppEnvironment", null)
                        .WithMany()
                        .HasForeignKey("AppEnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_identity_sessions_app_environments");

                    b.HasOne("Bullgate.Access.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_identity_sessions_identities");
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Identities.PasswordCredential", b =>
                {
                    b.HasOne("Bullgate.Access.Domain.Identities.Identity", null)
                        .WithOne()
                        .HasForeignKey("Bullgate.Access.Domain.Identities.PasswordCredential", "IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_credentials_identities");
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Identities.PasswordResetToken", b =>
                {
                    b.HasOne("Bullgate.Access.Domain.Topology.AppEnvironment", null)
                        .WithMany()
                        .HasForeignKey("AppEnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_tokens_app_environments");

                    b.HasOne("Bullgate.Access.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_tokens_identities");
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Identities.PhonePasswordResetChallenge", b =>
                {
                    b.HasOne("Bullgate.Access.Domain.Topology.AppEnvironment", null)
                        .WithMany()
                        .HasForeignKey("AppEnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_phone_password_reset_challenges_app_environments");

                    b.HasOne("Bullgate.Access.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_phone_password_reset_challenges_identities");
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Identities.PhoneRegistrationConflict", b =>
                {
                    b.HasOne("Bullgate.Access.Domain.Flows.AccessFlow", null)
                        .WithOne()
                        .HasForeignKey("Bullgate.Access.Domain.Identities.PhoneRegistrationConflict", "AccessFlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_phone_registration_conflicts_access_flows");

                    b.HasOne("Bullgate.Access.Domain.Identities.IdentityIdentifier", null)
                        .WithMany()
                        .HasForeignKey("ConflictingPhoneIdentifierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_phone_registration_conflicts_phone_identifier");

                    b.HasOne("Bullgate.Access.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("PreviousIdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_phone_registration_conflicts_previous_identity");
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Identities.ProofAttempt", b =>
                {
                    b.HasOne("Bullgate.Access.Domain.Identities.ProofChallenge", null)
                        .WithMany()
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proof_attempts_challenges");
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Identities.ProofChallenge", b =>
                {
                    b.HasOne("Bullgate.Access.Domain.Flows.AccessFlow", null)
                        .WithMany()
                        .HasForeignKey("AccessFlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proof_challenges_access_flows");

                    b.HasOne("Bullgate.Access.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_proof_challenges_identities");
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Identities.RegistrationContext", b =>
                {
                    b.HasOne("Bullgate.Access.Domain.Topology.AppEnvironment", null)
                        .WithMany()
                        .HasForeignKey("AppEnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_registration_contexts_app_environments");

                    b.HasOne("Bullgate.Access.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("RealmId", "IdentityId")
                        .HasPrincipalKey("RealmId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_registration_contexts_identities");
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Identities.SocialCredential", b =>
                {
                    b.HasOne("Bullgate.Access.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("RealmId", "IdentityId")
                        .HasPrincipalKey("RealmId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_social_credentials_identities");
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Topology.App", b =>
                {
                    b.HasOne("Bullgate.Access.Domain.Topology.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_apps_workspaces");
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Topology.AppEnvironment", b =>
                {
                    b.HasOne("Bullgate.Access.Domain.Topology.App", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "AppId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_app_environments_apps");

                    b.HasOne("Bullgate.Access.Domain.Topology.Realm", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "RealmId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_app_environments_realms");
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Topology.ApplicationClient", b =>
                {
                    b.HasOne("Bullgate.Access.Domain.Topology.AppEnvironment", null)
                        .WithMany()
                        .HasForeignKey("AppEnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_application_clients_app_environments");
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Topology.IntegrationClient", b =>
                {
                    b.HasOne("Bullgate.Access.Domain.Topology.AppEnvironment", null)
                        .WithMany()
                        .HasForeignKey("AppEnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_integration_clients_app_environments");
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Topology.IntegrationClientPermission", b =>
                {
                    b.HasOne("Bullgate.Access.Domain.Topology.IntegrationClient", null)
                        .WithMany()
                        .HasForeignKey("IntegrationClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_integration_client_permissions_clients");
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Topology.IntegrationClientSecret", b =>
                {
                    b.HasOne("Bullgate.Access.Domain.Topology.IntegrationClient", null)
                        .WithMany()
                        .HasForeignKey("IntegrationClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_integration_client_secrets_clients");
                });

            modelBuilder.Entity("Bullgate.Access.Domain.Topology.Realm", b =>
                {
                    b.HasOne("Bullgate.Access.Domain.Topology.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_realms_workspaces");
                });
#pragma warning restore 612, 618
        }
    }
}
